#!/bin/sh

#S40Network takes so long time that can't be monitored.
(/usr/bin/psplash-write "PROGRESS 10"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 20"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 30"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 40"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 50"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 60"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 70"; \
sleep 1; \
/usr/bin/psplash-write "PROGRESS 80") &
